### ISSUE TITLE
Allow ignore unknown launcher args 

### ISSUE THREAD

**Issue by thincal** [predibase/lorax#343]
### Feature request

When switch from TGI to lorax, there are already existed args passed in from client side but they are not supported in lorax yet. To let it work with less integration effort, is that feasible to introduce `ignore-unknown-args` with just a warning log ?

such as error:
```
Input validation error: `decoder_input_details` == true is not supported when streaming tokens
```

### Motivation

decrease the integration effort.

### Your contribution

possible to prepare a PR.

**Comment by tgaddair** [comment]
Hey @thincal, thanks for the feature request. That might be difficult to do on the server side, due to how the deserialization of requests works. We could do something on the client side in the Python client if you're using that.

I'd also be happy to take a look at which params are not supported from TGI and add them in if there are particular params your scripts are using.

**Comment by thincal** [comment]
> Input validation error: `decoder_input_details` == true is not supported when streaming tokens

Sorry the root cause is this param can't be used with stream mode, the validation rule is existed in both lorax and tgi:
```
#[error("`decoder_input_details` == true is not supported when streaming tokens")]
```

I need investigate the issue in my client side, thanks.

**Comment by thincal** [comment]
it's client that passing decoder_input_details=true in streaming mode, close this issue.
